apiVersion: monitoring.coreos.com/v1 
kind: PodMonitor
metadata:
  name: kafka-podmonintor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kafka
  selector:
    matchLabels:
      strimzi.io/component-type: kafka-exporter
      strimzi.io/name: my-cluster-kafka-exporter
  podMetricsEndpoints:
  - port: tcp-prometheus
    path: /metrics

